# Generated by Django 3.0.1 on 2020-02-14 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saldo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.IntegerField(default=100000)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeadlineParkir',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deadline', models.CharField(max_length=30, null=True)),
                ('parkir', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Parkir')),
            ],
        ),
    ]
