# Generated by Django 3.0.1 on 2020-02-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_deadlineparkir_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldo',
            name='saldo',
            field=models.IntegerField(default=0),
        ),
    ]
